# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('designation', models.CharField(choices=[('pm', 'Project Manager'), ('po', 'Product Owner'), ('ba', 'Business Analyst'), ('sm', 'Scrum Master'), ('fe', 'Front End Developer'), ('be', 'Back End Developer'), ('fs', 'Full Stack Developer'), ('mt', 'Manual Tester'), ('at', 'Automation Tester')], default='pm', max_length=256)),
                ('joining_date', models.DateTimeField(blank=True, null=True)),
                ('relieving_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
